"""add products and listings

Revision ID: 17700887cc2d
Revises: 
Create Date: 2026-08-27 15:34:34.351419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('category', sa.Enum('GPU', 'CPU', 'MAINBOARD', 'RAM', 'SSD', 'PSU', 'CASE', 'COOLER', 'COMPLETE_PC', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('canonical_model', sa.String(length=160), nullable=False),
    sa.Column('variant', sa.String(length=120), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('mpn', sa.String(length=120), nullable=True),
    sa.Column('ebay_product_id', sa.String(length=120), nullable=True),
    sa.Column('windows_11_status', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'canonical_model', 'variant', name='uq_product_variant')
    )
    op.create_table('raw_listings',
    sa.Column('source', sa.Enum('EBAY_DE', 'KLEINANZEIGEN_DE', 'MANUAL', name='marketplace'), nullable=False),
    sa.Column('external_id', sa.String(length=240), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_title', sa.String(length=500), nullable=False),
    sa.Column('raw_description', sa.String(length=8000), nullable=False),
    sa.Column('asking_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('shipping_cents', sa.BigInteger(), nullable=False),
    sa.Column('raw_condition', sa.String(length=120), nullable=False),
    sa.Column('location_summary', sa.String(length=240), nullable=False),
    sa.Column('payload_checksum', sa.String(length=80), nullable=False),
    sa.Column('import_method', sa.String(length=40), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', 'payload_checksum', name='uq_raw_payload')
    )
    op.create_index('ix_raw_listing_source_capture', 'raw_listings', ['source', 'captured_at'], unique=False)
    op.create_table('listing_observations',
    sa.Column('raw_listing_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('asking_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('shipping_cents', sa.BigInteger(), nullable=False),
    sa.Column('condition', sa.Enum('USED', 'REFURBISHED', 'UNTESTED', 'DEFECTIVE', 'UNKNOWN', name='condition'), nullable=False),
    sa.Column('sale_format', sa.String(length=40), nullable=False),
    sa.Column('seller_type', sa.String(length=40), nullable=True),
    sa.Column('model_match_confidence_bps', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['raw_listings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_listing_id')
    )
    op.create_table('product_aliases',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_alias', sa.String(length=240), nullable=False),
    sa.Column('required_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias', name='uq_product_alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_aliases')
    op.drop_table('listing_observations')
    op.drop_index('ix_raw_listing_source_capture', table_name='raw_listings')
    op.drop_table('raw_listings')
    op.drop_table('products')
    # ### end Alembic commands ###
    # Native Postgres ENUM types are not dropped automatically by op.drop_table.
    sa.Enum(name='condition').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='marketplace').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='productcategory').drop(op.get_bind(), checkfirst=True)
