"""add market and evaluations

Revision ID: 48b6d11e6089
Revises: 0001
Create Date: 2026-08-27 15:36:54.866607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_profiles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tax_profile', sa.Enum('PRIVATE', 'SMALL_BUSINESS', 'STANDARD_VAT', 'MARGIN_SCHEME', name='taxprofiletype'), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_rules',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matcher', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('required_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reserve_adjustment_bps', sa.Integer(), nullable=False),
    sa.Column('recommendation_cap', sa.String(length=40), nullable=True),
    sa.Column('explanation', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_comparables',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source', postgresql.ENUM('EBAY_DE', 'KLEINANZEIGEN_DE', 'MANUAL', name='marketplace', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', name='comparablestatus'), nullable=False),
    sa.Column('condition', postgresql.ENUM('USED', 'REFURBISHED', 'UNTESTED', 'DEFECTIVE', 'UNKNOWN', name='condition', create_type=False), nullable=False),
    sa.Column('item_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('shipping_cents', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('variant_match_confidence_bps', sa.Integer(), nullable=False),
    sa.Column('source_quality', sa.String(length=40), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('sold_through_bps', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_snapshots',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('cost_profile_id', sa.Uuid(), nullable=False),
    sa.Column('cost_profile_version', sa.Integer(), nullable=False),
    sa.Column('risk_rule_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparable_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('downside_resale_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_resale_cents', sa.BigInteger(), nullable=False),
    sa.Column('optimistic_resale_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_profit_cents', sa.BigInteger(), nullable=False),
    sa.Column('downside_profit_cents', sa.BigInteger(), nullable=False),
    sa.Column('expected_roi_bps', sa.Integer(), nullable=False),
    sa.Column('maximum_purchase_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('liquidity_bps', sa.Integer(), nullable=False),
    sa.Column('market_confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=False),
    sa.Column('risk_reserve_cents', sa.BigInteger(), nullable=False),
    sa.Column('risk_severity', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('BUY', 'NEGOTIATE', 'WATCH', 'REJECT', name='recommendation'), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_profile_id'], ['cost_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_id'], ['listing_observations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_snapshots')
    op.drop_table('market_comparables')
    op.drop_table('risk_rules')
    op.drop_table('cost_profiles')
    # ### end Alembic commands ###
    # Native Postgres ENUM types are not dropped automatically by op.drop_table.
    sa.Enum(name='confidencelevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recommendation').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='comparablestatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='taxprofiletype').drop(op.get_bind(), checkfirst=True)
