"""add operations

Revision ID: 06a4dd9675f7
Revises: 0002
Create Date: 2026-08-27 15:38:59.933260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_pairings',
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('extension_origin', sa.String(length=240), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('job_runs',
    sa.Column('idempotency_key', sa.String(length=240), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('last_error_message', sa.String(length=500), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('watchlists',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('marketplace', postgresql.ENUM('EBAY_DE', 'KLEINANZEIGEN_DE', 'MANUAL', name='marketplace', create_type=False), nullable=False),
    sa.Column('category', postgresql.ENUM('GPU', 'CPU', 'MAINBOARD', 'RAM', 'SSD', 'PSU', 'CASE', 'COOLER', 'COMPLETE_PC', 'OTHER', name='productcategory', create_type=False), nullable=False),
    sa.Column('include_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclude_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('serial_number', sa.String(length=240), nullable=True),
    sa.Column('acquisition_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('acquisition_costs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('condition_notes', sa.String(length=4000), nullable=False),
    sa.Column('disposition', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['listing_observations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_runs',
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('procedure_name', sa.String(length=160), nullable=False),
    sa.Column('tool_name', sa.String(length=160), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('measured_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.String(length=4000), nullable=False),
    sa.Column('evidence_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_runs')
    op.drop_table('alerts')
    op.drop_table('inventory_items')
    op.drop_table('watchlists')
    op.drop_table('job_runs')
    op.drop_table('extension_pairings')
    # ### end Alembic commands ###
